plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-wikirefs
  - jekyll-redirect-from
  - jekyll-minifier

include:
  - pages
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
exclude:
  - files

kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
  typographic_symbols:
    hellip: "..."
highlighter: rouge

incremental: false
